#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#
name: CI
# Trigger the workflow on push
on:
  push:
    branches:
      - master
jobs:
  docker-build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    env:
      IMAGE_FULL: quay.io/che-incubator/configbump:next
      CACHE_IMAGE_FULL: quay.io/che-incubator/configbump:cache
    steps:
    - uses: actions/checkout@v2
      name: Checkout configbump source code
    - name: Docker Buildx
      uses: crazy-max/ghaction-docker-buildx@v3.2.0
      with:
        buildx-version: v0.4.1
    - name: "Docker Quay.io Login"
      run:  docker login -u "${{ secrets.QUAY_USERNAME }}" -p "${{ secrets.QUAY_PASSWORD }}" quay.io
    - name: "Docker build with cache"
      run: |
         docker buildx build \
           --platform linux/amd64 \
           --cache-from "type=local,src=/tmp/.buildx-cache" \
           --cache-to "type=local,dest=/tmp/.buildx-cache" \
           --tag ${IMAGE_FULL} \
           --file build/dockerfiles/Dockerfile --push .
    - name: "Docker Logout"
      run: docker logout
    - name: Clear
      run: rm -f ${HOME}/.docker/config.json

